// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable disable

namespace WebApp.Models
{
    public partial class Class
    {
        public Class()
        {
            Students = new HashSet<Student>();
        }

        public string Id { get; set; }
        public string Name { get; set; }
        public string MajorId { get; set; }

        [JsonIgnore]
        public virtual Major MajorNavigation { get; set; }

        [JsonIgnore]
        public virtual ICollection<Student> Students { get; set; }
    }
}