// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace WebApp.Models
{
    public partial class Course
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Semester { get; set; }
        public int Hours { get; set; }
        public int Credit { get; set; }
        public string ExamMethod { get; set; }
    }
}