// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable disable

namespace WebApp.Models
{
    public partial class Major
    {
        public Major()
        {
            Classes = new HashSet<Class>();
        }

        public string Id { get; set; }
        public string Name { get; set; }

        [JsonIgnore]
        public virtual ICollection<Class> Classes { get; set; }
    }
}