// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable disable

namespace WebApp.Models
{
    public partial class Student
    {
        public string UserId { get; set; }
        public string SourcePlace { get; set; }
        public string ClassId { get; set; }
        public int? Credit { get; set; }

        [JsonIgnore]
        public virtual Class ClassNavigation { get; set; }

        [JsonIgnore]
        public virtual User UserNavigation { get; set; }
    }
}