// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace WebApp.Models
{
    public partial class StudentFull
    {
        public string StudentId { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public string Class { get; set; }
        public string ClassId { get; set; }
        public string Major { get; set; }
        public string MajorId { get; set; }
        public int? Credit { get; set; }
        public string SourcePlace { get; set; }
    }
}