// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable disable

namespace WebApp.Models
{
    public partial class StudentCourse
    {
        public string StudentId { get; set; }
        public string CourseId { get; set; }
        public int? Score { get; set; }

        [JsonIgnore]
        public virtual Course CourseNavigation { get; set; }

        [JsonIgnore]
        public virtual Student StudentNavigation { get; set; }
    }
}