// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable disable

namespace WebApp.Models
{
    public partial class TeacherCourse
    {
        public string TeacherId { get; set; }
        public string CourseId { get; set; }

        [JsonIgnore]
        public virtual Course CourseNavigation { get; set; }

        [JsonIgnore]
        public virtual Teacher TeacherNavigation { get; set; }
    }
}