// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable disable

namespace WebApp.Models
{
    public partial class User
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }

        [JsonIgnore]
        public virtual Student Student { get; set; }
        
        [JsonIgnore]
        public virtual Teacher Teacher { get; set; }
    }
}